name: po_editor_updater
description: PO Editor export and synchronization utility.
version: 0.2.2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  http: ^1.2.0
  yaml: ^3.1.0

dev_dependencies:
  flutter_lints: ^1.0.4
